global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'stockdata'
    replica: '0'


rule_files:
  - '/etc/prometheus/alerts/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Airflow 
  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']
      
  # API
  - job_name: 'stockdata-api'
    static_configs:
      - targets: ['stockdata-api:8888']
    metrics_path: '/metrics'
